site_name: Redux Toolkit
nav:
  - Start Here: index.md
  - Redux Flow: 1-redux-toolkit-explain.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages: ['lua', 'javascript', 'python', 'swift']
extra_css:
  - css/style.css
